version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: cmd-tools
      name: homebrew-tap

    commit_author:
      name: cmd-tools
      email: cmdtoolsowner@gmail.com

    folder: Formula
    homepage: "https://github.com/cmd-tools/gtfocli"
    description: " GTFO Command Line Interface for easy binaries search commands that can be used to bypass local security restrictions in misconfigured systems."
    license: "Apache License 2.0"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
